build-structure {
  "example-core" = {
    main-class = "my.shiny.app.MyApp"
    directory = "example/example-core/"
    scala-version = "2.13.9"
    dependencies = [
      {
        org = "com.softwaremill.sttp.tapir",
        module = "tapir-json-zio_2.13",
        version = "1.13.14"
      }
    ]
    prerequisites = []
  }

  "example-app" = {
    main-class = "my.shiny.app.HelloWorldZioHttpServer"
    directory = "example/example-app/"
    scala-version = "2.13.9"
    dependencies = [
      {
        org = "com.softwaremill.sttp.tapir",
        module = "tapir-core_2.13",
        version = "1.13.14"
      },
      {
        org = "com.softwaremill.sttp.tapir",
        module = "tapir-json-zio_2.13",
        version = "1.13.14"
      },
      {
        org = "com.softwaremill.sttp.tapir",
        module = "tapir-zio-http-server_2.13",
        version = "1.13.14"
      }
    ]
    prerequisites = ["example-core"]
  }
}