build-structure {
  name = "my-shiny-example"
  main-class = "my.shiny.app.App"
  directory = "example/"
  scala-version = "2.13.9"
  dependencies = [
    {
      org = "io.circe",
      module = "circe-core_2.13",
      version = "0.14.15"
    },
    {
      org = "io.circe",
      module = "circe-generic_2.13",
      version = "0.14.15"
    },
    {
      org = "io.circe",
      module = "circe-parser_2.13",
      version = "0.14.15"
    }
  ]
}