build-structure {
  name = "example-core"
  main-class = "my.shiny.app.MyApp"
  directory = "example-core/"
  scala-version = "2.13.9"
  dependencies = [
    {
      org = "com.softwaremill.sttp.tapir",
      module = "tapir-json-zio_2.13",
      version = "1.13.14"
    }
  ]
  prerequisites = []
}